Add multiple api path feature
muendiz/rest-art pull request #12
Opened 2018-07-12 20:22 UTC by furkanyilmazx

Please master merge to master

2018-07-13 11:57 UTC, enginustun requested changes
Please change meaningless strings in readme.

2018-07-13 11:57 UTC, enginustun commented on dev/modules/base-model.js
> +            .then((response) => { resolve({ response, request: request.xhr })})
Please rebase before starting development and double check the code you commit before opening a pull request...

lines: [151, 152]

2018-07-18 19:56 UTC, furkanyilmazx commented
Please master merge to master

2018-07-18 21:06 UTC, enginustun approved these changes

2018-07-18 21:10 UTC, merged